services:
    app:
        build: .
        container_name: app
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        environment:
            - "APP_ENV=local"
            - "APP_DEBUG=true"
            - "DB_CONNECTION=mysql"
            - "DB_HOST=db"
            - "DB_PORT=3306"
            - "DB_DATABASE=laravel"
            - "DB_USERNAME=user"
            - "DB_PASSWORD=111111"
        ports:
            - "9000:9000"

    db:
        image: mysql:8.0
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: 111111
        ports:
            - "3306:3306"
        volumes:
            - laravel_db_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    laravel_db_data:
